name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: List files in src directory
      run: dir src

    - name: Run PHP_CodeSniffer
      run: vendor/bin/phpcs --standard=PSR12 src/

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse src

    - name: Verifica sintaxe do src/factory.php
      run: php -l src/factory.php

